part of 'club_export_repository.dart';

List<_DatasetSpec> get _operationSpecs => const [
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/participantes.csv',
    table: 'euromillions_players',
    queryColumns: 'id,member_id,status,numbers,stars,created_at',
    exportColumns: [
      'id',
      'member_id',
      'status',
      'numbers',
      'stars',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/sorteios.csv',
    table: 'euromillions_draws',
    queryColumns: 'id,week,start_date,end_date,unit_cost,total_bet,prize,status,created_at',
    exportColumns: [
      'id',
      'week',
      'start_date',
      'end_date',
      'unit_cost',
      'total_bet',
      'prize',
      'status',
      'created_at',
    ],
    orderBy: 'start_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/chaves.csv',
    table: 'euromillions_keys',
    queryColumns: 'id,draw_id,numbers,stars',
    exportColumns: [
      'id',
      'draw_id',
      'numbers',
      'stars',
    ],
    parentSource: 'euromillions_draws',
    parentColumn: 'draw_id',
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/participacoes.csv',
    table: 'euromillions_participations',
    queryColumns: 'id,draw_id,member_id,amount,paid,paid_at,billing_frequency,numbers,stars,paid_amount,balance,active,payment_method,transaction_id',
    exportColumns: [
      'id',
      'draw_id',
      'member_id',
      'amount',
      'paid',
      'paid_at',
      'billing_frequency',
      'numbers',
      'stars',
      'paid_amount',
      'balance',
      'active',
      'payment_method',
      'transaction_id',
    ],
    parentSource: 'euromillions_draws',
    parentColumn: 'draw_id',
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/resultados.csv',
    table: 'euromillions_results',
    queryColumns: 'id,draw_date,numbers,stars,official_draw_number,prize_table,source,imported_at',
    exportColumns: [
      'id',
      'draw_date',
      'numbers',
      'stars',
      'official_draw_number',
      'prize_table',
      'source',
      'imported_at',
    ],
    orderBy: 'draw_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/cobrancas.csv',
    table: 'euromillions_draw_charges',
    queryColumns: 'id,player_id,week_start,draw_date,amount,paid_amount,paid_at,payment_method,transaction_id',
    exportColumns: [
      'id',
      'player_id',
      'week_start',
      'draw_date',
      'amount',
      'paid_amount',
      'paid_at',
      'payment_method',
      'transaction_id',
    ],
    orderBy: 'draw_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/multas.csv',
    table: 'euromillions_fines',
    queryColumns: 'id,result_id,player_id,missed_numbers,missed_stars,fine_amount,paid_amount,paid_at,payment_method,transaction_id',
    exportColumns: [
      'id',
      'result_id',
      'player_id',
      'missed_numbers',
      'missed_stars',
      'fine_amount',
      'paid_amount',
      'paid_at',
      'payment_method',
      'transaction_id',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.lottery,
    path: 'euromilhoes/premios.csv',
    table: 'euromillions_prizes',
    queryColumns: 'id,result_id,player_id,category,matched_numbers,matched_stars,prize_amount,received_amount,received_at,payment_method,transaction_id',
    exportColumns: [
      'id',
      'result_id',
      'player_id',
      'category',
      'matched_numbers',
      'matched_stars',
      'prize_amount',
      'received_amount',
      'received_at',
      'payment_method',
      'transaction_id',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.events,
    path: 'eventos/eventos.csv',
    table: 'events',
    queryColumns: 'id,name,description,location,starts_at,ends_at,status,capacity,budget,event_mode_enabled,created_at',
    exportColumns: [
      'id',
      'name',
      'description',
      'location',
      'starts_at',
      'ends_at',
      'status',
      'capacity',
      'budget',
      'event_mode_enabled',
      'created_at',
    ],
    orderBy: 'starts_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.events,
    path: 'eventos/inscricoes.csv',
    table: 'event_registrations',
    queryColumns: 'id,event_id,member_id,guest_name,status,checked_in_at,notes,created_at',
    exportColumns: [
      'id',
      'event_id',
      'member_id',
      'guest_name',
      'status',
      'checked_in_at',
      'notes',
      'created_at',
    ],
    parentSource: 'events',
    parentColumn: 'event_id',
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.events,
    path: 'eventos/voluntarios.csv',
    table: 'event_volunteers',
    queryColumns: 'id,event_id,member_id,function_name,status,created_at',
    exportColumns: [
      'id',
      'event_id',
      'member_id',
      'function_name',
      'status',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.events,
    path: 'eventos/parceiros.csv',
    table: 'event_partners',
    queryColumns: 'id,event_id,partner_type,name,contact_name,phone,email,agreed_value,paid_value,notes',
    exportColumns: [
      'id',
      'event_id',
      'partner_type',
      'name',
      'contact_name',
      'phone',
      'email',
      'agreed_value',
      'paid_value',
      'notes',
    ],
    parentSource: 'events',
    parentColumn: 'event_id',
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/produtos.csv',
    table: 'products',
    queryColumns: 'id,name,sku,category,unit,cost,sale_price,minimum_stock,active,current_stock,reserved_stock,inventory_area,description,supplier,photo_path,institutional_delivery,purchase_unit,consumption_unit,units_per_purchase,purchase_cost',
    exportColumns: [
      'id',
      'name',
      'sku',
      'category',
      'unit',
      'cost',
      'sale_price',
      'minimum_stock',
      'active',
      'current_stock',
      'reserved_stock',
      'inventory_area',
      'description',
      'supplier',
      'institutional_delivery',
      'purchase_unit',
      'consumption_unit',
      'units_per_purchase',
      'purchase_cost',
    ],
    orderBy: 'name',
    fileBucket: 'inventory-media',
    filePathColumn: 'photo_path',
    fileArchiveFolder: 'ficheiros/inventory-media/produtos',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/variantes.csv',
    table: 'product_variants',
    queryColumns: 'id,product_id,name,sku,attributes,active,current_stock,reserved_stock,minimum_stock,cost,sale_price,photo_path',
    exportColumns: [
      'id',
      'product_id',
      'name',
      'sku',
      'attributes',
      'active',
      'current_stock',
      'reserved_stock',
      'minimum_stock',
      'cost',
      'sale_price',
    ],
    parentSource: 'products',
    parentColumn: 'product_id',
    fileBucket: 'inventory-media',
    filePathColumn: 'photo_path',
    fileArchiveFolder: 'ficheiros/inventory-media/variantes',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/imagens_produtos.csv',
    table: 'product_images',
    queryColumns: 'id,product_id,variant_id,storage_path,is_primary',
    exportColumns: [
      'id',
      'product_id',
      'variant_id',
      'is_primary',
    ],
    orderBy: 'created_at',
    fileBucket: 'inventory-media',
    filePathColumn: 'storage_path',
    fileArchiveFolder: 'ficheiros/inventory-media/produtos',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/categorias.csv',
    table: 'inventory_categories',
    queryColumns: 'id,area,name,active',
    exportColumns: [
      'id',
      'area',
      'name',
      'active',
    ],
    orderBy: 'name',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/precos.csv',
    table: 'inventory_prices',
    queryColumns: 'id,product_id,audience,price',
    exportColumns: [
      'id',
      'product_id',
      'audience',
      'price',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/visibilidade.csv',
    table: 'inventory_visibility',
    queryColumns: 'id,product_id,audience,allowed',
    exportColumns: [
      'id',
      'product_id',
      'audience',
      'allowed',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/localizacoes.csv',
    table: 'inventory_locations',
    queryColumns: 'id,name,description,active,location_type,event_id,parent_id',
    exportColumns: [
      'id',
      'name',
      'description',
      'active',
      'location_type',
      'event_id',
      'parent_id',
    ],
    orderBy: 'name',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/stock_localizacoes.csv',
    table: 'inventory_stock_balances',
    queryColumns: 'id,product_id,variant_id,location_id,quantity,reserved_quantity',
    exportColumns: [
      'id',
      'product_id',
      'variant_id',
      'location_id',
      'quantity',
      'reserved_quantity',
    ],
    orderBy: 'updated_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/movimentos.csv',
    table: 'stock_movements',
    queryColumns: 'id,product_id,variant_id,event_id,kind,quantity,unit_cost,notes,created_at,from_location_id,to_location_id,transfer_group_id',
    exportColumns: [
      'id',
      'product_id',
      'variant_id',
      'event_id',
      'kind',
      'quantity',
      'unit_cost',
      'notes',
      'created_at',
      'from_location_id',
      'to_location_id',
      'transfer_group_id',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/encomendas.csv',
    table: 'shop_orders',
    queryColumns: 'id,member_id,external_name,external_contact,status,total_amount,paid_amount,notes,created_at',
    exportColumns: [
      'id',
      'member_id',
      'external_name',
      'external_contact',
      'status',
      'total_amount',
      'paid_amount',
      'notes',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/encomendas_linhas.csv',
    table: 'shop_order_items',
    queryColumns: 'id,order_id,product_id,variant_id,quantity,unit_price',
    exportColumns: [
      'id',
      'order_id',
      'product_id',
      'variant_id',
      'quantity',
      'unit_price',
    ],
    parentSource: 'shop_orders',
    parentColumn: 'order_id',
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/encomendas_pagamentos.csv',
    table: 'shop_order_payments',
    queryColumns: 'id,order_id,amount,payment_method,treasury_transaction_id,created_at',
    exportColumns: [
      'id',
      'order_id',
      'amount',
      'payment_method',
      'treasury_transaction_id',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/patrimonio.csv',
    table: 'inventory_assets',
    queryColumns: 'id,asset_number,name,category,description,acquisition_date,acquisition_value,supplier,condition,location_id,responsible_member_id,photo_path,warranty_until,last_maintenance_at,next_maintenance_at,active,notes,current_value,brand,model,serial_number,qr_code,requires_inspection,inspection_interval_months,last_inspection_at,next_inspection_at,custom_attributes',
    exportColumns: [
      'id',
      'asset_number',
      'name',
      'category',
      'description',
      'acquisition_date',
      'acquisition_value',
      'supplier',
      'condition',
      'location_id',
      'responsible_member_id',
      'warranty_until',
      'last_maintenance_at',
      'next_maintenance_at',
      'active',
      'notes',
      'current_value',
      'brand',
      'model',
      'serial_number',
      'qr_code',
      'requires_inspection',
      'inspection_interval_months',
      'last_inspection_at',
      'next_inspection_at',
      'custom_attributes',
    ],
    orderBy: 'asset_number',
    fileBucket: 'inventory-media',
    filePathColumn: 'photo_path',
    fileArchiveFolder: 'ficheiros/inventory-media/patrimonio',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/patrimonio_imagens.csv',
    table: 'asset_images',
    queryColumns: 'id,asset_id,storage_path,image_type,is_primary',
    exportColumns: [
      'id',
      'asset_id',
      'image_type',
      'is_primary',
    ],
    orderBy: 'created_at',
    fileBucket: 'inventory-media',
    filePathColumn: 'storage_path',
    fileArchiveFolder: 'ficheiros/inventory-media/patrimonio',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/patrimonio_eventos.csv',
    table: 'asset_events',
    queryColumns: 'id,asset_id,event_type,title,description,metadata,created_at',
    exportColumns: [
      'id',
      'asset_id',
      'event_type',
      'title',
      'description',
      'metadata',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/patrimonio_emprestimos.csv',
    table: 'asset_loans',
    queryColumns: 'id,asset_id,borrower_type,member_id,event_id,external_name,loaned_at,expected_return_at,returned_at,notes,returned_condition,return_notes',
    exportColumns: [
      'id',
      'asset_id',
      'borrower_type',
      'member_id',
      'event_id',
      'external_name',
      'loaned_at',
      'expected_return_at',
      'returned_at',
      'notes',
      'returned_condition',
      'return_notes',
    ],
    orderBy: 'loaned_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/patrimonio_manutencao.csv',
    table: 'asset_maintenance',
    queryColumns: 'id,asset_id,maintenance_date,maintenance_type,description,cost,supplier,next_due_date,account_id,payment_method,treasury_transaction_id',
    exportColumns: [
      'id',
      'asset_id',
      'maintenance_date',
      'maintenance_type',
      'description',
      'cost',
      'supplier',
      'next_due_date',
      'account_id',
      'payment_method',
      'treasury_transaction_id',
    ],
    orderBy: 'maintenance_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/patrimonio_kits.csv',
    table: 'asset_kits',
    queryColumns: 'id,name,description,active,created_at',
    exportColumns: [
      'id',
      'name',
      'description',
      'active',
      'created_at',
    ],
    orderBy: 'name',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/patrimonio_kits_itens.csv',
    table: 'asset_kit_items',
    queryColumns: 'kit_id,asset_id,quantity',
    exportColumns: [
      'kit_id',
      'asset_id',
      'quantity',
    ],
    parentSource: 'asset_kits',
    parentColumn: 'kit_id',
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/contagens.csv',
    table: 'inventory_count_sessions',
    queryColumns: 'id,name,location_id,event_id,status,notes,started_by,started_at,completed_by,completed_at',
    exportColumns: [
      'id',
      'name',
      'location_id',
      'event_id',
      'status',
      'notes',
      'started_by',
      'started_at',
      'completed_by',
      'completed_at',
    ],
    orderBy: 'started_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/contagens_linhas.csv',
    table: 'inventory_count_items',
    queryColumns: 'id,session_id,product_id,variant_id,theoretical_qty,counted_qty,difference,unit_cost,notes,photo_path,recounted,counted_by,counted_at',
    exportColumns: [
      'id',
      'session_id',
      'product_id',
      'variant_id',
      'theoretical_qty',
      'counted_qty',
      'difference',
      'unit_cost',
      'notes',
      'recounted',
      'counted_by',
      'counted_at',
    ],
    parentSource: 'inventory_count_sessions',
    parentColumn: 'session_id',
    fileBucket: 'inventory-media',
    filePathColumn: 'photo_path',
    fileArchiveFolder: 'ficheiros/inventory-media/contagens',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/bar_operacoes.csv',
    table: 'bar_operations',
    queryColumns: 'id,product_id,event_id,operation_type,purchase_units,consumption_quantity,unit_price,total_amount,payment_method,notes,treasury_transaction_id,created_at',
    exportColumns: [
      'id',
      'product_id',
      'event_id',
      'operation_type',
      'purchase_units',
      'consumption_quantity',
      'unit_price',
      'total_amount',
      'payment_method',
      'notes',
      'treasury_transaction_id',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/bar_sessoes.csv',
    table: 'bar_consumption_sessions',
    queryColumns: 'id,event_id,source,status,notes,created_at,confirmed_at',
    exportColumns: [
      'id',
      'event_id',
      'source',
      'status',
      'notes',
      'created_at',
      'confirmed_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.inventory,
    path: 'inventario/bar_sessoes_linhas.csv',
    table: 'bar_consumption_session_items',
    queryColumns: 'id,session_id,product_id,quantity,operation_type,unit_price,notes,created_at',
    exportColumns: [
      'id',
      'session_id',
      'product_id',
      'quantity',
      'operation_type',
      'unit_price',
      'notes',
      'created_at',
    ],
    parentSource: 'bar_consumption_sessions',
    parentColumn: 'session_id',
    collectIds: false,
  ),
];
