part of 'club_export_repository.dart';

List<_DatasetSpec> get _memberFinanceSpecs => const [
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/membros.csv',
    table: 'members',
    queryColumns: 'id,member_number,full_name,nickname,email,phone,birth_date,joined_at,status,prospect_joined_at,full_colors_at,primary_role,additional_roles,photo_path',
    exportColumns: [
      'id',
      'member_number',
      'full_name',
      'nickname',
      'email',
      'phone',
      'birth_date',
      'joined_at',
      'status',
      'prospect_joined_at',
      'full_colors_at',
      'primary_role',
      'additional_roles',
    ],
    orderBy: 'member_number',
    fileBucket: 'member-photos',
    filePathColumn: 'photo_path',
    fileArchiveFolder: 'ficheiros/member-photos',
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/dados_sensiveis.csv',
    table: 'members',
    queryColumns: 'id,member_number,full_name,tax_number,address,postal_code,locality,emergency_contact,notes',
    exportColumns: [
      'id',
      'member_number',
      'full_name',
      'tax_number',
      'address',
      'postal_code',
      'locality',
      'emergency_contact',
      'notes',
    ],
    collectIds: false,
    sensitive: true,
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/motas.csv',
    table: 'member_motorcycles',
    queryColumns: 'id,member_id,brand,model,year,registration,nickname,primary_motorcycle,active,acquired_on,retired_on,notes',
    exportColumns: [
      'id',
      'member_id',
      'brand',
      'model',
      'year',
      'registration',
      'nickname',
      'primary_motorcycle',
      'active',
      'acquired_on',
      'retired_on',
      'notes',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/cargos.csv',
    table: 'member_positions',
    queryColumns: 'id,member_id,position_id,is_primary,starts_at,ends_at',
    exportColumns: [
      'id',
      'member_id',
      'position_id',
      'is_primary',
      'starts_at',
      'ends_at',
    ],
    orderBy: 'starts_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/estados_historico.csv',
    table: 'member_status_history',
    queryColumns: 'id,member_id,old_status,new_status,changed_at,changed_by,notes',
    exportColumns: [
      'id',
      'member_id',
      'old_status',
      'new_status',
      'changed_at',
      'changed_by',
      'notes',
    ],
    orderBy: 'changed_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/timeline.csv',
    table: 'member_timeline',
    queryColumns: 'id,member_id,event_type,title,description,event_date,visibility,source_type,source_id',
    exportColumns: [
      'id',
      'member_id',
      'event_type',
      'title',
      'description',
      'event_date',
      'visibility',
      'source_type',
      'source_id',
    ],
    orderBy: 'event_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/patches.csv',
    table: 'member_patch_awards',
    queryColumns: 'id,member_id,product_id,variant_id,patch_name,variant_name,status,requested_at,approved_at,delivered_at,delivery_location_name,notes',
    exportColumns: [
      'id',
      'member_id',
      'product_id',
      'variant_id',
      'patch_name',
      'variant_name',
      'status',
      'requested_at',
      'approved_at',
      'delivered_at',
      'delivery_location_name',
      'notes',
    ],
    orderBy: 'requested_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/manutencao.csv',
    table: 'maintenance_records',
    queryColumns: 'id,member_id,motorcycle_id,service_date,service_type,description,odometer_km,workshop,cost,next_service_date,next_service_km,notes',
    exportColumns: [
      'id',
      'member_id',
      'motorcycle_id',
      'service_date',
      'service_type',
      'description',
      'odometer_km',
      'workshop',
      'cost',
      'next_service_date',
      'next_service_km',
      'notes',
    ],
    orderBy: 'service_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.members,
    path: 'membros/manutencao_anexos.csv',
    table: 'maintenance_attachments',
    queryColumns: 'id,member_id,maintenance_id,storage_path,original_file_name,mime_type,file_size',
    exportColumns: [
      'id',
      'member_id',
      'maintenance_id',
      'original_file_name',
      'mime_type',
      'file_size',
    ],
    orderBy: 'created_at',
    fileBucket: 'member-maintenance',
    filePathColumn: 'storage_path',
    fileNameColumn: 'original_file_name',
    fileSizeColumn: 'file_size',
    fileArchiveFolder: 'ficheiros/member-maintenance',
  ),
  _DatasetSpec(
    section: ClubExportSection.treasury,
    path: 'tesouraria/contas.csv',
    table: 'treasury_accounts',
    queryColumns: 'id,name,account_type,iban,opening_balance,opening_date,active,allows_negative',
    exportColumns: [
      'id',
      'name',
      'account_type',
      'iban',
      'opening_balance',
      'opening_date',
      'active',
      'allows_negative',
    ],
    orderBy: 'name',
  ),
  _DatasetSpec(
    section: ClubExportSection.treasury,
    path: 'tesouraria/categorias.csv',
    table: 'treasury_categories',
    queryColumns: 'id,name,direction,active',
    exportColumns: [
      'id',
      'name',
      'direction',
      'active',
    ],
    orderBy: 'name',
  ),
  _DatasetSpec(
    section: ClubExportSection.treasury,
    path: 'tesouraria/centros_custo.csv',
    table: 'cost_centers',
    queryColumns: 'id,name,code,active',
    exportColumns: [
      'id',
      'name',
      'code',
      'active',
    ],
    orderBy: 'name',
  ),
  _DatasetSpec(
    section: ClubExportSection.treasury,
    path: 'tesouraria/movimentos.csv',
    table: 'treasury_transactions',
    queryColumns: 'id,kind,account_id,destination_account_id,category_id,cost_center_id,event_id,transaction_date,description,amount,payment_method,notes,source_type,source_id,reversal_of,created_at',
    exportColumns: [
      'id',
      'kind',
      'account_id',
      'destination_account_id',
      'category_id',
      'cost_center_id',
      'event_id',
      'transaction_date',
      'description',
      'amount',
      'payment_method',
      'notes',
      'source_type',
      'source_id',
      'reversal_of',
      'created_at',
    ],
    orderBy: 'transaction_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.financial,
    path: 'financeiro/pedidos.csv',
    table: 'financial_requests',
    queryColumns: 'id,member_id,request_type,category,batch_id,amount,description,due_date,status,review_note,payment_method,treasury_account_id,treasury_transaction_id,submitted_at,paid_at,source_type,source_id,created_at',
    exportColumns: [
      'id',
      'member_id',
      'request_type',
      'category',
      'batch_id',
      'amount',
      'description',
      'due_date',
      'status',
      'review_note',
      'payment_method',
      'treasury_account_id',
      'treasury_transaction_id',
      'submitted_at',
      'paid_at',
      'source_type',
      'source_id',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.financial,
    path: 'financeiro/pedidos_anexos.csv',
    table: 'financial_request_attachments',
    queryColumns: 'id,request_id,kind,storage_path,original_file_name,mime_type,file_size,created_at',
    exportColumns: [
      'id',
      'request_id',
      'kind',
      'original_file_name',
      'mime_type',
      'file_size',
      'created_at',
    ],
    orderBy: 'created_at',
    fileBucket: 'financial-documents',
    filePathColumn: 'storage_path',
    fileNameColumn: 'original_file_name',
    fileSizeColumn: 'file_size',
    fileArchiveFolder: 'ficheiros/financial-documents',
  ),
  _DatasetSpec(
    section: ClubExportSection.financial,
    path: 'financeiro/documentos_movimentos.csv',
    table: 'financial_transaction_documents',
    queryColumns: 'id,transaction_id,document_type,origin,storage_path,original_file_name,mime_type,file_size,is_primary,created_at',
    exportColumns: [
      'id',
      'transaction_id',
      'document_type',
      'origin',
      'original_file_name',
      'mime_type',
      'file_size',
      'is_primary',
      'created_at',
    ],
    orderBy: 'created_at',
    fileBucket: 'financial-documents',
    filePathColumn: 'storage_path',
    fileNameColumn: 'original_file_name',
    fileSizeColumn: 'file_size',
    fileArchiveFolder: 'ficheiros/financial-documents',
  ),
  _DatasetSpec(
    section: ClubExportSection.fees,
    path: 'quotas/planos.csv',
    table: 'fee_plans',
    queryColumns: 'id,name,amount,frequency,due_day,active',
    exportColumns: [
      'id',
      'name',
      'amount',
      'frequency',
      'due_day',
      'active',
    ],
    orderBy: 'name',
  ),
  _DatasetSpec(
    section: ClubExportSection.fees,
    path: 'quotas/obrigacoes.csv',
    table: 'fee_obligations',
    queryColumns: 'id,member_id,fee_plan_id,reference_year,reference_month,due_date,amount,paid_amount,status,notes,obligation_type',
    exportColumns: [
      'id',
      'member_id',
      'fee_plan_id',
      'reference_year',
      'reference_month',
      'due_date',
      'amount',
      'paid_amount',
      'status',
      'notes',
      'obligation_type',
    ],
    orderBy: 'due_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.fees,
    path: 'quotas/pagamentos.csv',
    table: 'fee_payments',
    queryColumns: 'id,obligation_id,transaction_id,amount,paid_at,received_by,notes',
    exportColumns: [
      'id',
      'obligation_id',
      'transaction_id',
      'amount',
      'paid_at',
      'received_by',
      'notes',
    ],
    orderBy: 'paid_at',
  ),
];
