part of 'club_export_repository.dart';

List<_DatasetSpec> get _supportSpecs => const [
  _DatasetSpec(
    section: ClubExportSection.documents,
    path: 'documentos/documentos.csv',
    table: 'documents',
    queryColumns: 'id,name,category,description,document_date,version,status,expires_at,sensitive,tags,linked_entity_type,linked_entity_id,storage_path,original_file_name,mime_type,file_size,created_at,updated_at',
    exportColumns: [
      'id',
      'name',
      'category',
      'description',
      'document_date',
      'version',
      'status',
      'expires_at',
      'sensitive',
      'tags',
      'linked_entity_type',
      'linked_entity_id',
      'original_file_name',
      'mime_type',
      'file_size',
      'created_at',
      'updated_at',
    ],
    orderBy: 'created_at',
    sensitiveFilter: false,
    fileBucket: 'club-documents',
    filePathColumn: 'storage_path',
    fileNameColumn: 'original_file_name',
    fileSizeColumn: 'file_size',
    fileArchiveFolder: 'ficheiros/club-documents',
  ),
  _DatasetSpec(
    section: ClubExportSection.documents,
    path: 'documentos/documentos_sensiveis.csv',
    table: 'documents',
    queryColumns: 'id,name,category,description,document_date,version,status,expires_at,sensitive,tags,linked_entity_type,linked_entity_id,storage_path,original_file_name,mime_type,file_size,created_at,updated_at',
    exportColumns: [
      'id',
      'name',
      'category',
      'description',
      'document_date',
      'version',
      'status',
      'expires_at',
      'sensitive',
      'tags',
      'linked_entity_type',
      'linked_entity_id',
      'original_file_name',
      'mime_type',
      'file_size',
      'created_at',
      'updated_at',
    ],
    orderBy: 'created_at',
    collectIds: false,
    sensitive: true,
    sensitiveFilter: true,
    fileBucket: 'club-documents',
    filePathColumn: 'storage_path',
    fileNameColumn: 'original_file_name',
    fileSizeColumn: 'file_size',
    fileArchiveFolder: 'ficheiros/club-documents/sensiveis',
  ),
  _DatasetSpec(
    section: ClubExportSection.communication,
    path: 'comunicacao/comunicados.csv',
    table: 'announcements',
    queryColumns: 'id,title,body,priority,audience,published_at,expires_at,requires_acknowledgement,created_at,updated_at',
    exportColumns: [
      'id',
      'title',
      'body',
      'priority',
      'audience',
      'published_at',
      'expires_at',
      'requires_acknowledgement',
      'created_at',
      'updated_at',
    ],
    orderBy: 'published_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.communication,
    path: 'comunicacao/confirmacoes_leitura.csv',
    table: 'announcement_acknowledgements',
    queryColumns: 'id,announcement_id,profile_id,acknowledged_at,created_at',
    exportColumns: [
      'id',
      'announcement_id',
      'profile_id',
      'acknowledged_at',
      'created_at',
    ],
    orderBy: 'acknowledged_at',
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.agenda,
    path: 'agenda/itens.csv',
    table: 'agenda_items',
    queryColumns: 'id,item_type,title,description,starts_at,ends_at,all_day,location,audience,priority,status,created_at,updated_at',
    exportColumns: [
      'id',
      'item_type',
      'title',
      'description',
      'starts_at',
      'ends_at',
      'all_day',
      'location',
      'audience',
      'priority',
      'status',
      'created_at',
      'updated_at',
    ],
    orderBy: 'starts_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.weeklyOfficer,
    path: 'oficial_semana/jantares.csv',
    table: 'weekly_dinners',
    queryColumns: 'id,dinner_date,dinner_kind,status,assigned_member_id,external_name,dish,notes,assignment_source,generated,created_at,updated_at',
    exportColumns: [
      'id',
      'dinner_date',
      'dinner_kind',
      'status',
      'assigned_member_id',
      'external_name',
      'dish',
      'notes',
      'assignment_source',
      'generated',
      'created_at',
      'updated_at',
    ],
    orderBy: 'dinner_date',
  ),
  _DatasetSpec(
    section: ClubExportSection.weeklyOfficer,
    path: 'oficial_semana/rotacao.csv',
    table: 'weekly_officer_rotation',
    queryColumns: 'id,member_id,rotation_order,enabled,availability_status,force_included,joined_rotation_at,notes,created_at,updated_at',
    exportColumns: [
      'id',
      'member_id',
      'rotation_order',
      'enabled',
      'availability_status',
      'force_included',
      'joined_rotation_at',
      'notes',
      'created_at',
      'updated_at',
    ],
    orderBy: 'rotation_order',
  ),
  _DatasetSpec(
    section: ClubExportSection.weeklyOfficer,
    path: 'oficial_semana/ausencias.csv',
    table: 'weekly_officer_absences',
    queryColumns: 'id,member_id,absence_kind,starts_on,ends_on,notes,created_at,updated_at',
    exportColumns: [
      'id',
      'member_id',
      'absence_kind',
      'starts_on',
      'ends_on',
      'notes',
      'created_at',
      'updated_at',
    ],
    orderBy: 'starts_on',
  ),
  _DatasetSpec(
    section: ClubExportSection.weeklyOfficer,
    path: 'oficial_semana/trocas.csv',
    table: 'weekly_officer_swap_requests',
    queryColumns: 'id,dinner_id,requester_member_id,requested_member_id,status,requester_note,response_note,manager_note,responded_at,responded_by,applied_at,applied_by,created_at,updated_at',
    exportColumns: [
      'id',
      'dinner_id',
      'requester_member_id',
      'requested_member_id',
      'status',
      'requester_note',
      'response_note',
      'manager_note',
      'responded_at',
      'responded_by',
      'applied_at',
      'applied_by',
      'created_at',
      'updated_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.configuration,
    path: 'configuracao/clube.csv',
    table: 'clubs',
    queryColumns: 'id,name,legal_name,slug,primary_color,currency,timezone,active,created_at,updated_at',
    exportColumns: [
      'id',
      'name',
      'legal_name',
      'slug',
      'primary_color',
      'currency',
      'timezone',
      'active',
      'created_at',
      'updated_at',
    ],
    directClubId: true,
  ),
  _DatasetSpec(
    section: ClubExportSection.configuration,
    path: 'configuracao/cargos.csv',
    table: 'club_positions',
    queryColumns: 'id,code,name,sort_order,active,created_at,updated_at',
    exportColumns: [
      'id',
      'code',
      'name',
      'sort_order',
      'active',
      'created_at',
      'updated_at',
    ],
    orderBy: 'sort_order',
  ),
  _DatasetSpec(
    section: ClubExportSection.configuration,
    path: 'configuracao/permissoes_cargos.csv',
    table: 'club_role_permissions',
    queryColumns: 'role_key,permission_key,allowed,updated_at,created_at',
    exportColumns: [
      'role_key',
      'permission_key',
      'allowed',
      'updated_at',
      'created_at',
    ],
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.configuration,
    path: 'configuracao/parametros.csv',
    table: 'club_settings',
    queryColumns: 'id,key,value,created_at,updated_at',
    exportColumns: [
      'id',
      'key',
      'value',
      'created_at',
      'updated_at',
    ],
    orderBy: 'key',
  ),
  _DatasetSpec(
    section: ClubExportSection.configuration,
    path: 'configuracao/acessos.csv',
    table: 'club_memberships',
    queryColumns: 'id,profile_id,access_role,active,created_at,updated_at',
    exportColumns: [
      'id',
      'profile_id',
     'access_role',
      'active',
      'created_at',
      'updated_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.configuration,
    path: 'configuracao/excecoes_permissoes.csv',
    table: 'user_permission_overrides',
    queryColumns: 'profile_id,permission_key,allowed,updated_at,created_at',
    exportColumns: [
      'profile_id',
      'permission_key',
      'allowed',
      'updated_at',
      'created_at',
    ],
    collectIds: false,
  ),
  _DatasetSpec(
    section: ClubExportSection.audit,
    path: 'auditoria/audit_log.csv',
    table: 'audit_log',
    queryColumns: 'id,actor_id,entity_type,entity_id,action,created_at',
    exportColumns: [
      'id',
      'actor_id',
      'entity_type',
      'entity_id',
      'action',
      'created_at',
    ],
    orderBy: 'created_at',
  ),
  _DatasetSpec(
    section: ClubExportSection.audit,
    path: 'auditoria/atividade.csv',
    table: 'activity_feed',
    queryColumns: 'id,actor_id,activity_type,title,description,entity_type,entity_id,created_at',
    exportColumns: [
      'id',
      'actor_id',
      'activity_type',
      'title',
     'description',
      'entity_type',
      'entity_id',
     'created_at',
    ],
    orderBy: 'created_at',
  ),
];
